language: python
python:
   - 2.6
   - 2.7
   - 3.2
   - 3.3
   - 3.4
   - pypy
   - pypy3

install:
   - "pip install ."
   - "pip install -r requirements.txt"
   
script: "behave"

notifications:
   email: false
